[package]
name = "plbi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "plbi"
path = "src/lib.rs"

[[bin]]
name = "plbi"
path = "src/main.rs"


[build-dependencies] 
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"
# lalrpop = "0.20.0"
# The link_qt_object_files feature is required for statically linking Qt 6.
cxx-qt-build = { version = "0.6", features = [ "link_qt_object_files" ] }


[dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"
cxx-qt = "0.6.0"
cxx = "1.0.95"
cxx-qt-lib = "0.6"
# lalrpop-util = { version = "0.20.0", features = ["lexer", "unicode"] }
polars = { version = "0.37.0", features = ["lazy", "csv", "json", "parquet"] }

