
use std::string::String;
use crate::grammar::ast::{Ast, LoadableFormatData, CSVData};

grammar;

pub Start: Ast = {
    "load_files" <f:ScanFileNames> => Ast{ loadable_filenames: f }
};

ScanFileNames: Vec<LoadableFormatData> = {
    <v:(<FileNameData>)*> => v
};

FileNameData: LoadableFormatData = {
    "CSV" "(" "filename" "=" <f:FileNameId> ")" => LoadableFormatData::CSV(CSVData{filename:<>, separator: None})
} 

FileNameId: String = {
    r"[0-9a-zA-z/.]+" => String::from(<>)
};

